---

# installing Node/npm is required for the neovim Ansible role,
# in order to install and build vscode-php-debug,
# for the PHP debugger

- name: download nodejs repository configuration tool
  get_url:
    url:  https://deb.nodesource.com/setup_25.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755' # anyone can execute

- name: configure nodejs repository
  shell: /tmp/nodesource_setup.sh

- name: install nodejs and npm from repo
  apt: name="{{ item }}"
    state=present
    update_cache='yes'
  with_items:
    - nodejs
